# Generated by Django 4.0.1 on 2022-01-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
